### ISSUE TITLE
Info - Format only changed lines with Git & File history

### ISSUE THREAD

**Issue by Shubham29012001** [jellydn/lazy-nvim-ide#4]
Hello, I've been using your config setup IDE with my custom changes and I loved it.

a) However, I am finding it a little challenging to setup the format on save to only format changed lines (tracked using git) and if it's not git initialized repo, we can format the whole open file.
b) More detailed git file history to check previous commits to a particular open file.

Can anyone please help me with this?

**Comment by jellydn** [comment]
Hi @Shubham29012001 Thank you for opening this issue however it would recommend you open the issue with https://github.com/lazyvim/lazyvim or https://github.com/stevearc/conform.nvim
