### ISSUE TITLE
default page when opening 

### ISSUE THREAD

**Issue by createanArray1** [jellydn/lazy-nvim-ide#5]
is there a way to disable the default menu that pops up when opening nvim? couldnt find it in the config options.

**Comment by jellydn** [comment]
Could you share the screenshot? @createanArray1

**Comment by createanArray1** [comment]
![Screenshot from 2024-04-19 20-56-04](https://github.com/jellydn/lazy-nvim-ide/assets/89856787/30706ad3-07d6-47de-af77-781071808848)

**Comment by createanArray1** [comment]
so very sorry, meant to put this in the copilot chat repo
